services:
  traefik:
    image: traefik:v2.10
    restart: unless-stopped
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
  db:
    image: mysql:5.7.44
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./storage/mysql/data:/var/lib/mysql

  hm-products-ms:
    build:
      context: ./repositories/hm-products-ms
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    volumes:
      - ./repositories/hm-products-ms:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    volumes:
      - ./repositories/hm-products-ms:/var/www
      - ./nginx/:/etc/nginx/conf.d/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webserver.rule=Host(`dev.haxielmalave.org`)"
      - "traefik.http.routers.webserver.entrypoints=websecure"
      - "traefik.http.routers.webserver.tls.certresolver=selfresolver"
      - "traefik.http.services.webserver.loadbalancer.server.port=80"

networks:
  default:
    driver: bridge
    name: dev.haxielmalave.internal
    ipam:
      config:
        - subnet: 172.57.0.0/24
      driver: default
