api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  selfresolver:
    acme:
      email: malavehaxiel96@gmail.com
      storage: /letsencrypt/acme.json
      tlsChallenge: true